package com.olegovichhh.audioconverter
import android.content.*; import android.net.Uri; import android.os.Bundle; import android.provider.OpenableColumns; import android.view.View; import android.widget.*; import androidx.activity.result.contract.ActivityResultContracts; import androidx.appcompat.app.AppCompatActivity; import com.arthenica.ffmpegkit.FFmpegKit; import com.arthenica.ffmpegkit.ReturnCode; import java.io.File
class MainActivity:AppCompatActivity(){
 private var inputUri:Uri?=null; private var pendingFile:File?=null
 private lateinit var fileText:TextView; private lateinit var status:TextView; private lateinit var progress:ProgressBar; private lateinit var format:Spinner; private lateinit var bitrate:Spinner; private lateinit var mono:CheckBox
 private val picker=registerForActivityResult(ActivityResultContracts.OpenDocument()){u->u?:return@registerForActivityResult; inputUri=u; contentResolver.takePersistableUriPermission(u,Intent.FLAG_GRANT_READ_URI_PERMISSION); fileText.text=displayName(u); status.text="Файл выбран"}
 private val saver=registerForActivityResult(ActivityResultContracts.CreateDocument("audio/*")){u->val f=pendingFile;if(u!=null&&f!=null){contentResolver.openOutputStream(u)!!.use{d->f.inputStream().use{it.copyTo(d)}};status.text="Файл сохранён"}}
 override fun onCreate(b:Bundle?){super.onCreate(b);setContentView(R.layout.activity_main);fileText=findViewById(R.id.fileText);status=findViewById(R.id.statusText);progress=findViewById(R.id.progress);format=findViewById(R.id.formatSpinner);bitrate=findViewById(R.id.bitrateSpinner);mono=findViewById(R.id.monoCheck);format.adapter=ArrayAdapter(this,android.R.layout.simple_spinner_dropdown_item,listOf("mp3","m4a","aac","wav","flac","ogg","opus"));bitrate.adapter=ArrayAdapter(this,android.R.layout.simple_spinner_dropdown_item,listOf("64k","96k","128k","192k","256k","320k"));findViewById<Button>(R.id.pickButton).setOnClickListener{picker.launch(arrayOf("audio/*","audio/midi","application/octet-stream"))};findViewById<Button>(R.id.convertButton).setOnClickListener{convert()};if(intent.getBooleanExtra("pick_file",false)){window.decorView.post{picker.launch(arrayOf("audio/*","audio/midi","application/octet-stream"))}}}
 private fun convert(){val u=inputUri?:run{toast("Сначала выберите файл");return};val n=displayName(u);if(n.endsWith(".mid",true)||n.endsWith(".midi",true)){status.text="MIDI требует SoundFont-синтезатора. MIDI renderer будет добавлен следующим модулем.";return};progress.visibility=View.VISIBLE;status.text="Обработка…";Thread{try{val i=File(cacheDir,"input_audio");contentResolver.openInputStream(u)!!.use{s->i.outputStream().use{s.copyTo(it)}};val e=format.selectedItem.toString();val o=File(cacheDir,"converted."+e);val br=bitrate.selectedItem.toString();val ch=if(mono.isChecked)" -ac 1" else "";val c=when(e){"mp3"->"libmp3lame";"m4a","aac"->"aac";"flac"->"flac";"ogg"->"libvorbis";"opus"->"libopus";"wav"->"pcm_s16le";else->"copy"};val q=if(e=="wav"||e=="flac")"" else " -b:a "+br;val cmd="-y -i \""+i.absolutePath+"\" -vn -c:a "+c+q+ch+" \""+o.absolutePath+"\"";val s=FFmpegKit.execute(cmd);if(!ReturnCode.isSuccess(s.returnCode))error(s.output?:"FFmpeg error");runOnUiThread{progress.visibility=View.GONE;status.text="Готово. Выберите, куда сохранить.";pendingFile=o;saver.launch("converted."+e)}}catch(e:Exception){runOnUiThread{progress.visibility=View.GONE;status.text="Ошибка: "+e.message}}}.start()}
 private fun displayName(u:Uri):String{contentResolver.query(u,null,null,null,null)?.use{c->val i=c.getColumnIndex(OpenableColumns.DISPLAY_NAME);if(c.moveToFirst()&&i>=0)return c.getString(i)};return u.lastPathSegment?:"audio"}
 private fun toast(s:String)=Toast.makeText(this,s,Toast.LENGTH_SHORT).show()
}